SENSOR_CONFIGS = [
    {
        "name": "Motor Temperature",
        "unit": "°C",
        "start_value": 40.0,
        "min_value": 20.0,
        "max_value": 120.0,
        "noise_range": 0.3,
        "anomaly_chance": 97,
        "anomaly_magnitude": (8, 15),
        "warning_limit": 70,
        "critical_limit": 90,
    },
    {
        "name": "Vibration",
        "unit": "mm/s",
        "start_value": 2.0,
        "min_value": 0.0,
        "max_value": 20.0,
        "noise_range": 0.2,
        "anomaly_chance": 98,
        "anomaly_magnitude": (3, 7),
        "warning_limit": 6,
        "critical_limit": 10,
    },
    {
        "name": "RPM",
        "unit": "rpm",
        "start_value": 1200.0,
        "min_value": 0.0,
        "max_value": 3000.0,
        "noise_range": 20.0,
        "anomaly_chance": 99,
        "anomaly_magnitude": (200, 500),
        "warning_limit": 2200,
        "critical_limit": 2600,
    },
]